### ISSUE TITLE
Shows with an apostrophe in the title require two apostrophes entered when adding to block

### ISSUE THREAD

**Issue by MoeFwacky** [amazingr4b/TBN-Plex#17] opened 2016-09-11 17:09 UTC
Just a minor thing, but when adding a show like Bob's Burgers, I have to type Bob''s Burgers or it's not found. Also minor is the display when added doubles that. Output below:

Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 2
TV Show Name:bob's burgers
bob's burgers not found in library. Did you mean:

Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 2
TV Show Name:bob''s burgers
Bob''''s Burgers has been added to the block.

**Comment by MoeFwacky** [comment] 2016-09-12 03:15
A secondary issue I ran into with this is the show failed to launch. piplaystate.py required a bit of manual input (which could be an issue when it's running from the cron job and not in a terminal window) to move forward, then failed to play the item. Here's the output below, after it played the commercial, it failed to play the show and moved on to the next one in the block.

Doing a session check.
Stopped
Assuming you meant Bob's burgers
Did you mean:

1:Bob''s Burgers

2: Quit
Choice: 1
Bob''s Burgers
Starting the block.sunday e

Doing a session check.
Stopped

**Comment by amazingr4b** [comment] 2016-09-12 13:58
The double apostrophe is an SQLite thing. I thought I had that check everywhere, but I guess I missed a spot or two. I'll make a note and go through and update that function at some point.

**Comment by amazingr4b** [comment] 2016-09-18 02:25
This should be fixed now, though I wasn't able to do much testing since I have almost no items with apostrophes in them.

**Comment by MoeFwacky** [comment] 2016-09-21 02:21
I'm still running into issues with shows with an apostrophe. The start of this block has Bob's Burgers up next. When trying to either skip or see what's next, I get the following output

pi@BAD-HORSE ~/hasystem $ whatupnext
Traceback (most recent call last):
  File "/home/pi/hasystem/system.py", line 5313, in <module>
    say = whatupnext()
  File "/home/pi/hasystem/system.py", line 3867, in whatupnext
    episode = nextep(block)
  File "/home/pi/hasystem/system.py", line 4154, in nextep
    ssn = str(ep[0])
TypeError: 'NoneType' object has no attribute '__getitem__'
pi@BAD-HORSE ~/hasystem $ skipthat
Traceback (most recent call last):
  File "/home/pi/hasystem/system.py", line 5350, in <module>
    say = skipthat()
  File "/home/pi/hasystem/system.py", line 4240, in skipthat
    check = whatupnext()
  File "/home/pi/hasystem/system.py", line 3867, in whatupnext
    episode = nextep(block)
  File "/home/pi/hasystem/system.py", line 4154, in nextep
    ssn = str(ep[0])
TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by amazingr4b** [comment] 2016-09-21 02:59
I'm not able to duplicate that error using my shows/movies with an apostrophe. Do an explainblock on it and post the output. I'm guessing when the items in that block were added before changes were made, and that is causing some missmatch error. This is what mine looks like for reference:  

pi@raspberrypi:/var/www/html $ setplaymode test3
Playmode has been set to Block Package Mode: Test3
pi@raspberrypi:/var/www/html $ whatupnext
Up next we have da vinci''s demons, Season 1, Episode 1, The Hanged Man
pi@raspberrypi:/var/www/html $ explainblock
The Test3 plays the following:
Da Vinci's Demons
the movie dante's peak


Item 1, da vinci''s demons is next: Up next we have da vinci''s demons, Season 1, Episode 1, The Hanged Man

**Comment by MoeFwacky** [comment] 2016-09-21 03:05
Here's the explainblock for that block. I actually flushed the install and recreated it again, so none of these should have been in before the fix.

The tuesday_e plays the following:
Bob''s Burgers
Archer (2009)
Breaking Bad
Seinfeld
Downton Abbey

**Comment by amazingr4b** [comment] 2016-09-21 03:17
I'm guessing you made that using the method where it asks questions to make a block? If that is the case I know what the problem is. Right now it's likely going to fail the check so you can't just remove "bob''s burgers" and then readd it using addtoblock. The single command to add a block with an item should work in the mean time. Try removing and remaking it with "addblock tuesday_e "bob's burgers"". If you then explainblock on that, and it outputs it with the single ' it should be usable.

**Comment by amazingr4b** [comment] 2016-09-21 03:28
Give the newest file a try. Either way should work now. This is what i get now for the walkthough way I never use:  

pi@raspberrypi:~/hasystem $ addblock
Command line options not present. Proceeding to querry mode.
Enter New Block Name

Name: Test4
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 2
TV Show Name:da vinci's demons
Da Vinci''s Demons has been added to the block.
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 1
Movie Name:dante's peak
The movie dante''s peak has been added to the block.
Adding 1- Movie or 2- TV Show 3- Random Item Type to the list? 4- Quit.
Choice: 4
block.Test4 has been created.
pi@raspberrypi:~/hasystem $ explainblock
The Test3 plays the following:
Da Vinci's Demons
the movie dante's peak


Item 2, movie.dante''s peak is next: Up next we have The Movie dante''s peak
pi@raspberrypi:~/hasystem $ setplaymode Test4
Playmode has been set to Block Package Mode: Test4
pi@raspberrypi:~/hasystem $ whatupnext
Up next we have da vinci''s demons, Season 1, Episode 2, The Serpent
pi@raspberrypi:~/hasystem $ skipthat
Up next we have The Movie dante''s peak

**Comment by MoeFwacky** [comment] 2016-09-21 06:47
Looks like that did the trick. Thanks

**Comment by amazingr4b** [comment] 2016-09-29 04:24
I'm closing this case. If this pops up as in issue somewhere else feel free to open a new case.

**Closed by amazingr4b** 2016-09-29 04:24 UTC
Labels: enhancement
